---
- name: playbook_zsh.yml - zsh and zim setup
  hosts: all

  tasks:
    - name: install base zsh and curl
      become: yes
      pacman:
        update_cache: yes
        name:
          - zsh
          - curl

    - name: change shell
      become: yes
      user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh

    - name: check if zimfw is already installed
      stat:
        path: "{{ ansible_facts.env.HOME }}/.zim/zimfw.zsh"
      register: zimfw_installed

    - name: install zimfw using its script
      shell: "curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh"
      args:
        executable: /usr/bin/zsh
      when: not zimfw_installed.stat.exists

    - name: ensure steeef theme module is in .zimrc
      lineinfile:
        path: "{{ ansible_facts.env.HOME }}/.zimrc"
        line: "zmodule steeef"
        create: yes
      register: zimrc_updated

    - name: run zimfw install to apply module changes
      shell: "zsh -ic 'zimfw install'"
      # to source .zshrc "zsh -ic" is used, otherwise "command not found: zimfw"
      args:
        executable: /usr/bin/zsh
      when: not zimfw_installed.stat.exists or zimrc_updated.changed

    - name: copy .myownrc
      copy:
        src: ./.myownrc
        dest: "{{ ansible_facts.env.HOME }}/.myownrc"
        mode: '0644'

    - name: source .myownrc in .zshrc
      lineinfile:
        path: "{{ ansible_facts.env.HOME }}/.zshrc"
        line: 'source ~/.myownrc'
        create: yes

    - name: add common commands to zsh history
      lineinfile:
        path: "{{ ansible_facts.env.HOME }}/.zhistory"
        line: "{{ item }}"
        create: yes
        mode: '0600'
      loop:
        - "sudo reboot now"
        - "sudo shutdown now"
        - "sudo pacman -Sy archlinux-keyring"
        - "sudo chown $USER:$USER"
        - "sudo chmod +x"
        - "sudo chmod -R u=rwX,go=rX ."
