---
- name: test
  hosts: all
  become: yes

  tasks:

# LOCATE THE QUICK FILE SEARCH------------------------------------------------

    - name: get virtual enviroment info
      command: /usr/bin/systemd-detect-virt
      register: virtualization_type

    - name: if vmware, install open-vm-tools
      pacman:
        name:
          - open-vm-tools
      when: virtualization_type.stdout == 'vmware'

    - name: if vmware, enable and start vmware open tools services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
          - vmtoolsd.service
          - vmware-vmblock-fuse.service
      when: virtualization_type.stdout == 'vmware'





      # - name: restart sensu-services
      #   service:
      #     name: "{{ item }}"
      #     state: restarted
      #   with_items:
      #     - sensu-api
      #     - sensu-client
      #     - sensu-server


   # - name: Facts
   #   setup:
   # - name: Dump
   #   run_once: true
   #   copy:
   #     content: "{{ hostvars[inventory_hostname] | to_nice_json }}"
   #     dest: /tmp/setup-dump53.json
   #   when: ansible_virtualization_type == 'VMware'



# - hosts: node1
#   gather_facts: yes
#   tasks:
#    - name: Check File
#      shell: ls -ld /etc/postfix/post-install
#      register: result
#      ignore_errors: yes

#    - name: Define Variable
#      set_fact:
#          exists: "{{ result.stdout }}"
#      when: result|success

#    - name: Display Variable
#      debug: msg="{{ exists }}"
#      ignore_errors: yes
